import { Notification, NotificationPreferences } from "@/types/notifications";

// Helper to create dates relative to now
export const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);
export const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);

export const mockNotifications: Notification[] = [
  {
    id: "n-1",
    type: "meeting_reminder",
    primaryText: "Leadership Sync starts in 15 minutes",
    contextText: "10:00 AM - Conference Room A",
    createdAt: hoursAgo(0.25),
    isRead: false,
    link: "/departments/1",
  },
  {
    id: "n-2",
    type: "action_item_due",
    primaryText: "Review Q1 roadmap priorities is due today",
    contextText: "From Leadership Sync meeting",
    createdAt: hoursAgo(2),
    isRead: false,
    link: "/departments/1#action-items",
  },
  {
    id: "n-3",
    type: "mention",
    primaryText: "Sarah Chen mentioned you in a comment",
    contextText: "Design Review agenda item",
    createdAt: hoursAgo(3),
    isRead: false,
    link: "/departments/3",
  },
  {
    id: "n-4",
    type: "comment",
    primaryText: "New comment on Sprint Planning",
    contextText: "Mike Williams: 'Let's discuss the timeline'",
    createdAt: hoursAgo(5),
    isRead: true,
    link: "/departments/2",
  },
  {
    id: "n-5",
    type: "assignment",
    primaryText: "You were assigned to a new action item",
    contextText: "Prepare Q2 budget proposal",
    createdAt: hoursAgo(8),
    isRead: true,
    link: "/departments/1#action-items",
  },
  {
    id: "n-6",
    type: "meeting_reminder",
    primaryText: "Design Review tomorrow at 1:00 PM",
    contextText: "5 agenda items to review",
    createdAt: daysAgo(1),
    isRead: false,
    link: "/departments/3",
  },
  {
    id: "n-7",
    type: "comment",
    primaryText: "Alex Johnson replied to your comment",
    contextText: "Engineering Standup discussion",
    createdAt: daysAgo(1),
    isRead: true,
    link: "/departments/2",
  },
  {
    id: "n-8",
    type: "action_item_due",
    primaryText: "Finalize component library designs overdue",
    contextText: "Was due 2 days ago",
    createdAt: daysAgo(2),
    isRead: true,
    link: "/departments/3#action-items",
  },
  {
    id: "n-9",
    type: "mention",
    primaryText: "Emily Davis tagged you in Marketing Meeting",
    contextText: "Re: Campaign budget allocation",
    createdAt: daysAgo(3),
    isRead: true,
    link: "/departments/4",
  },
  {
    id: "n-10",
    type: "assignment",
    primaryText: "New task assigned: Security audit review",
    contextText: "Infrastructure Review meeting",
    createdAt: daysAgo(5),
    isRead: true,
    link: "/departments/2#action-items",
  },
  // Additional notifications for a fuller experience
  {
    id: "n-11",
    type: "meeting_reminder",
    primaryText: "Sales Pipeline Review in 30 minutes",
    contextText: "8:30 AM - Virtual Meeting",
    createdAt: hoursAgo(0.5),
    isRead: false,
    link: "/departments/5",
  },
  {
    id: "n-12",
    type: "comment",
    primaryText: "Lisa Wang commented on your proposal",
    contextText: "Product Roadmap discussion",
    createdAt: hoursAgo(4),
    isRead: false,
    link: "/departments/6",
  },
  {
    id: "n-13",
    type: "action_item_due",
    primaryText: "Submit expense report due tomorrow",
    contextText: "From Operations meeting",
    createdAt: daysAgo(1),
    isRead: false,
    link: "/departments/1#action-items",
  },
  {
    id: "n-14",
    type: "mention",
    primaryText: "David Kim mentioned you in Engineering",
    contextText: "Architecture decisions thread",
    createdAt: daysAgo(4),
    isRead: true,
    link: "/departments/2",
  },
  {
    id: "n-15",
    type: "assignment",
    primaryText: "Assigned: Update API documentation",
    contextText: "Engineering Sprint Planning",
    createdAt: daysAgo(6),
    isRead: true,
    link: "/departments/2#action-items",
  },
  {
    id: "n-16",
    type: "meeting_reminder",
    primaryText: "Product Demo rescheduled to Friday",
    contextText: "2:00 PM - Main Conference Room",
    createdAt: daysAgo(7),
    isRead: true,
    link: "/departments/6",
  },
  {
    id: "n-17",
    type: "comment",
    primaryText: "New feedback on design mockups",
    contextText: "Kate Moore: 'Love the new color scheme'",
    createdAt: daysAgo(8),
    isRead: true,
    link: "/departments/3",
  },
  {
    id: "n-18",
    type: "action_item_due",
    primaryText: "Quarterly report submitted",
    contextText: "Completed on time",
    createdAt: daysAgo(10),
    isRead: true,
    link: "/departments/1#action-items",
  },
];

export const defaultNotificationPreferences: NotificationPreferences = {
  email: {
    enabled: true,
    types: {
      meeting_reminder: true,
      action_item_due: true,
      mention: true,
      comment: false,
      assignment: true,
    },
  },
  push: {
    enabled: true,
    types: {
      meeting_reminder: true,
      action_item_due: true,
      mention: true,
      comment: true,
      assignment: true,
    },
  },
  quietHours: {
    enabled: false,
    start: "22:00",
    end: "08:00",
  },
};
